StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60F08A876C6DF5A9}" {
   Id "SPC-Vehicle_BMP1_Name"
   Target_en_us "BMP-1 Infantry Fighting Vehicle"
   Modified 1626377723
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60F08A8771CE02CF}" {
   Id "SPC-Vehicle_BMP1P_Name"
   Target_en_us "BMP-1P Infantry Fighting Vehicle"
   Modified 1626377730
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
 }
}